name: CI - MoneyMap

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: moneymap_user
          POSTGRES_PASSWORD: moneymap_pass
          POSTGRES_DB: moneymap_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      # - name: Generate Prisma Client
      #   run: npx prisma generate

      # - name: Run Prisma Migrate
      #   run: npx prisma migrate deploy

      - name: Run lint
        run: npm run lint

      # - name: Run unit tests
      #   run: npm run test

      - name: Build app
        run: npm run build
